version = 0.1

[default.deploy.parameters]
stack_name = "walkfind-serverless"
resolve_s3 = true
s3_prefix = "walkfind-serverless"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "DbSecretArn=\"\""

[default.global.parameters]
region = "ap-northeast-1"
