version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DbSecretArn=\"arn:aws:secretsmanager:ap-northeast-1:844739519142:secret:/walkfind/database-HpiCzf\" CognitoIssuerUri=\"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_LVczdiFp6\" CognitoUserPoolArn=\"arn:aws:cognito-idp:ap-northeast-1:844739519142:userpool/ap-northeast-1_LVczdiFp6\""
image_repositories = ["EmbeddingWorkerFunctionV2=844739519142.dkr.ecr.ap-northeast-1.amazonaws.com/samapp7427b055/embeddingworkerfunctionv2f4f1259arepo"]

[default.global.parameters]
region = "ap-northeast-1"
